// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Resources;

// General Information
[assembly: AssemblyTitle("FalloutTerminal")]
[assembly: AssemblyDescription("A program to simplify hacking a terminal in Fallout 3 by showing remaining possibilities.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("AdituV")]
[assembly: AssemblyProduct("FalloutTerminal")]
[assembly: AssemblyCopyright("Copyright © Iris Ward 2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version informationr(
[assembly: AssemblyVersion("1.2.1.8")]
[assembly: AssemblyFileVersion("1.2.1.8")]
[assembly: NeutralResourcesLanguageAttribute( "en-US" )]

